services:
  web:
    image: node:22
    container_name: internship-web
    working_dir: /app
    volumes:
      - ./frontend:/app      
    command: ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
    ports:
      - "5173:5173"
